version: 2
jobs: 
  build: 

    working_directory: ~/circleci-demo-java-spring 

    docker: 
      - image: circleci/openjdk:11-stretch 

    steps: 

      - checkout 

      - run: mvn package 

      - store_test_results: 
          path: target/surefire-reports
